# Use the latest ubuntu image as base
FROM ubuntu:latest

# Update APT repositories
RUN apt-get update

# Upgrade installed packages
RUN apt-get upgrade -y

# Set the command to be run when the container starts
CMD ["echo", "Hello, World!"]
