version: '3'

services:
  back-end-1:
    image: your-back-end-image
    container_name: task6-back-end-1
    ports:
      - "5252"
    networks:
      - backend-network

  back-end-2:
    image: your-back-end-image
    container_name: task6-back-end-2
    ports:
      - "5252"
    networks:
      - backend-network

  front-end:
    image: your-front-end-image
    container_name: task6-front-end-1
    networks:
      - frontend-network

  proxy:
    image: your-nginx-image
    container_name: task6-proxy-1
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - back-end-1
      - back-end-2
    networks:
      - frontend-network
      - backend-network

networks:
  frontend-network:
  backend-network:
