version: '3.8'

services:
  front-end:
    build:
      context: .
      dockerfile: Dockerfile-front-end
    ports:
      - "9000:80"

  back-end:
    build:
      context: .
      dockerfile: Dockerfile-back-end
    ports:
      - "5252:5252"
